DELETE FROM TO_DO_LIST
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 1', 1)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 2', 1)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 3', 0)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 4', 1)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 5', 0)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 6', 1)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 7', 1)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 8', 1)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 9', 0)
INSERT INTO TO_DO_LIST (TO_DO, STATUS) VALUES ('to do list item 10', 1)

